FROM rust:slim-bookworm

RUN apt-get update && apt-get install -y \
    ca-certificates \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch --locked

WORKDIR /app

CMD ["cargo", "watch", "-w", "src", "-w", "migrations", "-x", "run"]
