[assets]
help = "help.png"
info = "info.png"
stats = "stats.png"
lastcall = "lastcall.png"
names = "names.png"
voicehistory = "voicehistory.png"
userinfo = "userinfo.png"
clearuser = "clearuser.png"
nuke = "nuke.gif"
lockdown = "lockdown.png"
verification = "verification.gif"
lookup = "lookup.png"
warnings = "warnings.png"
ticketpanel = "ticketpanel.png"
closeticket = "closeticket.png"
claimticket = "claimticket.png"
addticket = "addticket.png"
removeticket = "removeticket.png"
sync = "sync.png"
botstats = "botstats.png"
shutdown = "shutdown.png"
privacy = "privacy.png"
raidmode = "raidmode.png"
modules = "modules.png"
setup = "setup.png"
ticket = "ticket.png"
default = "default.png"
approved = "approved.webp"
rejected = "rejected.gif"
